import { Level } from './types';

export const LEVELS: Level[] = [
  {
    id: 1,
    title: "صياد الأرقام",
    subtitle: "التركيز البصري",
    description: "ساعد الأرنب ليصل إلى جزره بترتيب الأرقام الصحيح من 1 إلى 10.",
    message: "أنت بطل! لقد وجدت كل الأرقام.",
    theme: 'nature',
    nodes: [
      { id: '1', label: '1', type: 'number', x: 20, y: 20 },
      { id: '2', label: '2', type: 'number', x: 40, y: 25 },
      { id: '3', label: '3', type: 'number', x: 60, y: 15 },
      { id: '4', label: '4', type: 'number', x: 80, y: 30 },
      { id: '5', label: '5', type: 'number', x: 70, y: 50 },
      { id: '6', label: '6', type: 'number', x: 50, y: 45 },
      { id: '7', label: '7', type: 'number', x: 30, y: 60 },
      { id: '8', label: '8', type: 'number', x: 15, y: 80 },
      { id: '9', label: '9', type: 'number', x: 45, y: 85 },
      { id: '10', label: '10', type: 'number', x: 75, y: 75 },
    ],
    sequence: ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'],
  },
  {
    id: 2,
    title: "سائق السباق",
    subtitle: "سرعة المعالجة",
    description: "هل يمكنك كسر رقمك القياسي السابق؟ وصل الأرقام من 1 إلى 15 بسرعة!",
    message: "يا له من سباق سريع! أنت سائق محترف.",
    theme: 'racing',
    timeLimit: 30,
    nodes: [
      { id: '1', label: '1', type: 'number', x: 10, y: 10 },
      { id: '2', label: '2', type: 'number', x: 30, y: 20 },
      { id: '3', label: '3', type: 'number', x: 50, y: 10 },
      { id: '4', label: '4', type: 'number', x: 70, y: 25 },
      { id: '5', label: '5', type: 'number', x: 90, y: 15 },
      { id: '6', label: '6', type: 'number', x: 85, y: 45 },
      { id: '7', label: '7', type: 'number', x: 65, y: 55 },
      { id: '8', label: '8', type: 'number', x: 45, y: 40 },
      { id: '9', label: '9', type: 'number', x: 25, y: 50 },
      { id: '10', label: '10', type: 'number', x: 10, y: 70 },
      { id: '11', label: '11', type: 'number', x: 30, y: 85 },
      { id: '12', label: '12', type: 'number', x: 50, y: 75 },
      { id: '13', label: '13', type: 'number', x: 70, y: 90 },
      { id: '14', label: '14', type: 'number', x: 90, y: 70 },
      { id: '15', label: '15', type: 'number', x: 50, y: 50 },
    ],
    sequence: ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15'],
  },
  {
    id: 3,
    title: "لاعب السيرك",
    subtitle: "المرونة المعرفية",
    description: "اقفز بين منصة الأرقام ومنصة الحروف: 1 ثم أ، ثم 2 ثم ب...",
    message: "أداء مذهل! أنت لاعب سيرك حقيقي.",
    theme: 'circus',
    nodes: [
      { id: '1', label: '1', type: 'number', x: 20, y: 20, color: '#FFD700' },
      { id: 'A', label: 'أ', type: 'letter', x: 40, y: 15, color: '#32CD32' },
      { id: '2', label: '2', type: 'number', x: 60, y: 25, color: '#FFD700' },
      { id: 'B', label: 'ب', type: 'letter', x: 80, y: 20, color: '#32CD32' },
      { id: '3', label: '3', type: 'number', x: 75, y: 50, color: '#FFD700' },
      { id: 'C', label: 'ج', type: 'letter', x: 55, y: 45, color: '#32CD32' },
      { id: '4', label: '4', type: 'number', x: 35, y: 55, color: '#FFD700' },
      { id: 'D', label: 'د', type: 'letter', x: 15, y: 40, color: '#32CD32' },
      { id: '5', label: '5', type: 'number', x: 25, y: 80, color: '#FFD700' },
      { id: 'E', label: 'هـ', type: 'letter', x: 50, y: 85, color: '#32CD32' },
    ],
    sequence: ['1', 'A', '2', 'B', '3', 'C', '4', 'D', '5', 'E'],
  },
  {
    id: 4,
    title: "المحقق الذكي",
    subtitle: "التبديل المتغير",
    description: "اتبع القاعدة المتغيرة: رقم ثم لون. 1 ثم أحمر، 2 ثم أصفر...",
    message: "ذكاء خارق! لقد حللت اللغز يا محقق.",
    theme: 'detective',
    nodes: [
      { id: '1', label: '1', type: 'number', x: 15, y: 15 },
      { id: 'red', label: '', type: 'color', x: 35, y: 25, color: '#EF4444' },
      { id: '2', label: '2', type: 'number', x: 55, y: 10 },
      { id: 'yellow', label: '', type: 'color', x: 75, y: 20, color: '#FBBF24' },
      { id: '3', label: '3', type: 'number', x: 85, y: 45 },
      { id: 'blue', label: '', type: 'color', x: 65, y: 55, color: '#3B82F6' },
      { id: '4', label: '4', type: 'number', x: 45, y: 40 },
      { id: 'green', label: '', type: 'color', x: 25, y: 50, color: '#10B981' },
    ],
    sequence: ['1', 'red', '2', 'yellow', '3', 'blue', '4', 'green'],
  },
  {
    id: 5,
    title: "متاهة الأذكياء",
    subtitle: "المهام المركبة",
    description: "اتبع المسار السري: رقم - حرف - لون. هل يمكنك الوصول للنهاية؟",
    message: "أنت عبقري! لقد اجتزت المتاهة النهائية.",
    theme: 'maze',
    nodes: [
      { id: '1', label: '1', type: 'number', x: 10, y: 10 },
      { id: 'A', label: 'أ', type: 'letter', x: 30, y: 20 },
      { id: 'red-circle', label: '', type: 'color', x: 50, y: 10, color: '#EF4444', shape: 'circle' },
      { id: '2', label: '2', type: 'number', x: 70, y: 25 },
      { id: 'B', label: 'ب', type: 'letter', x: 90, y: 15 },
      { id: 'blue-circle', label: '', type: 'color', x: 85, y: 45, color: '#3B82F6', shape: 'circle' },
      { id: '3', label: '3', type: 'number', x: 65, y: 55 },
      { id: 'C', label: 'ج', type: 'letter', x: 45, y: 40 },
      { id: 'green-circle', label: '', type: 'color', x: 25, y: 50, color: '#10B981', shape: 'circle' },
    ],
    sequence: ['1', 'A', 'red-circle', '2', 'B', 'blue-circle', '3', 'C', 'green-circle'],
  },
];
